#!/bin/bash

## Check dependencies

check_failed=

type gawk &>/dev/null
if [[ $? -ne 0 ]]
then
	check_failed=true
	>&2 echo "The dependency gawk is missing. Run \"sudo apt install gawk\" to install it."
fi

type rofi &>/dev/null
if [[ $? -ne 0 ]]
then
	check_failed=true
	>&2 echo "The dependency rofi is missing. See https://github.com/davatorium/rofi/blob/next/INSTALL.md for instructions on how to install it."
fi

type jq &>/dev/null
if [[ $? -ne 0 ]]
then
	check_failed=true
	>&2 echo "The dependency jq is missing. Run \"sudo apt install jq\" to install it, or see https://stedolan.github.io/jq/download for further details."
fi

type youtube-dl &>/dev/null
if [[ $? -ne 0 ]] 
then
	check_failed=true
	>&2 echo "The dependency youtube-dl is missing. See https://github.com/ytdl-org/youtube-dl/blob/master/README.md#installation for instructions on how to install it."
fi

type mpv &>/dev/null
if [[ $? -ne 0 ]]
then
	check_failed=true
	>&2 echo "The dependency mpv is missing. Run \"sudo apt install mpv\" to install it, or see https://mpv.io/installation for further details."
fi

if [[ "$check_failed" ]]
then
	exit 1
fi

## Where am I?

script_path=$(realpath $0)
script_dir="$(dirname "$script_path")"
default_configfile="$script_dir/.default.config.json"

## Variable defaults

search_size=30
max_history_size=50
max_cache_age=60
data_dir=".data"
force_no_cache=false
force_no_history=false
subs_mode=false
wl_mode=false
reverse_mode=false
use_max_downloads=false

## (Re)write default config

jq -n --arg search_size "$search_size" --arg max_history_size "$max_history_size" --arg max_cache_age "$max_cache_age" --arg data_dir "$data_dir" --arg force_no_cache "$force_no_cache" --arg force_no_history "$force_no_history" --arg subs_mode "$subs_mode" --arg wl_mode "$wl_mode" --arg reverse_mode "$reverse_mode" --arg use_max_downloads "$use_max_downloads" '{search_size: $search_size, max_history_size: $max_history_size, max_cache_age: $max_cache_age, data_dir: $data_dir, force_no_cache: $force_no_cache, force_no_history: $force_no_history, subs_mode: $subs_mode, wl_mode: $wl_mode, reverse_mode: $reverse_mode, use_max_downloads: $use_max_downloads}' > "$default_configfile"

## Cleanup on exit
trap cleanup EXIT
cleanup () {
	echo "Exiting..."
	[[ -f "$temp_res" ]] &&	rm -f "$temp_res"
}

## Define functions

print_help () {
echo -en "The following options are available:
--generate-config: Generate a default configuration file and exit
--clear-history: Clear the search history and exit
--clear-cache: Clear the cache and exit
-s|--subs: Fetch videos from a YouTube account's subscription feed instead of using a search query
-wl|--watch-later: Fetch videos from a YouTube account's Watch Later playlist instead of using a search query
-n [num]|--search-size [num]: Fetch a maximum of num videos
-r|--reverse: Reverse the order of the displayed videos
--use-max-downloads: This uses youtube-dl's --max-downloads flag instead of --playlist-end internally (see configuration below)
-C|--force-no-cache: Prevent the program from reading from or writing to the cache
-H|--force-no-history: Disable the search history
--config [file]: Use file as the configuration file
-h|--help: Print help and exit"
}

find_config () {
	if [[ -s "$passed_configfile" ]]
	then
		echo "$passed_configfile"
	elif [[ -s "$script_dir/config.json" ]]
	then
		echo "$script_dir/config.json"
	elif [[ -s "$HOME/.config/yt-search-play/config.json" ]]
	then
		echo "$HOME/.config/yt-search-play/config.json"
	else
		echo "$default_configfile"
	fi
}

load_config () {
	configfile="$(find_config)"

	if [[ -n "$configfile" ]]
	then
		config=$(jq '.' "$configfile")
		
		if [[ -z "$config" ]]
		then
			>&2 echo "Error reading config in $configfile."
			exit 1
		fi

		search_size=$(echo "$config" | jq -r --arg default "$search_size" '. | if has("search_size") then .search_size else $default end')
		max_history_size=$(echo "$config" | jq -r --arg default "$max_history_size" '. | if has("max_history_size") then .max_history_size else $default end')
		max_cache_age=$(echo "$config" | jq -r --arg default "$max_cache_age" '. | if has("max_cache_age") then .max_cache_age else $default end')
		data_dir=$(echo "$config" | jq -r --arg default "$data_dir" '. | if has("data_dir") then .data_dir else $default end')
		force_no_cache=$(echo "$config" | jq -r --arg default "$force_no_cache" '. | if has("force_no_cache") then .force_no_cache else $default end')
		force_no_history=$(echo "$config" | jq -r --arg default "$force_no_history" '. | if has("force_no_history") then .force_no_history else $default end')
		subs_mode=$(echo "$config" | jq -r --arg default "$subs_mode" '. | if has("subs_mode") then .subs_mode else $default end')
		wl_mode=$(echo "$config" | jq -r --arg default "$wl_mode" '. | if has("wl_mode") then .wl_mode else $default end')
		reverse_mode=$(echo "$config" | jq -r --arg default "$reverse_mode" '. | if has("reverse_mode") then .reverse_mode else $default end')
		use_max_downloads=$(echo "$config" | jq -r --arg default "$use_max_downloads" '. | if has("use_max_downloads") then .use_max_downloads else $default end')
	fi

	if ! [[ "$search_size" =~ ^[0-9]+$ ]]
	then
		>&2 echo "Error in $configfile: search_size must be an integer."
		exit 1
	fi
	if ! [[ "$max_history_size" =~ ^[0-9]+$ ]]
	then
		>&2 echo "Error in $configfile: max_history_size must be an integer."
		exit 1
	fi
	if ! [[ "$max_cache_age" =~ ^[0-9]+$ ]]
	then
		>&2 echo "Error in $configfile: max_cache_age must be an integer."
		exit 1
	fi

	case $data_dir in
		/*) mkdir -p "$data_dir" ;;
		*) mkdir -p "$script_dir/$data_dir" ;;
	esac
	if [[ $? -ne 0 ]]
	then
		>&2 echo "Error in $configfile: $data_dir is not a valid directory."
		exit 1
	fi

	historyfile="$script_dir/$data_dir/search-history"
	cookiefile="$script_dir/$data_dir/cookies.txt"
	cachefile="$script_dir/$data_dir/cache.json"
	
	if [[ ! -f "$historyfile" ]]
	then
		touch -a "$historyfile"
	fi
	history_size=$(< "$historyfile" wc -l 2>/dev/null || echo 0)
	playlist_start=1
}

clear_history () {
	rm -f "$historyfile"
}

clear_cache () {
	rm -f "$cachefile"
}

update_history () {
	last_item="$(tail -n 1 "$historyfile")"
	if [[ -n "$search_query" ]]
	then
		sed -i '/'"$search_query"'/d' "$historyfile"
		echo "$search_query" >> "$historyfile"
	fi
	if [[ -n "$url" ]]
	then
		sed -i '/'"$selection"'/d' "$historyfile"
		echo "$selection" >> "$historyfile"
	fi

	if [[ $history_size -gt $max_history_size ]]
	then
		echo "$(tail -n $max_history_size "$historyfile")" > "$historyfile"
	fi
}

purge_expired_cache () {
	jq --arg time "$(($(date +%s)-$max_cache_age))" 'del(.[] | select(.time < $time))' "$cachefile" > "$cachefile.tmp" && mv "$cachefile.tmp" "$cachefile"
}

write_to_cache () {
	if [[ ! -s "$cachefile" ]] || [[ -z "$(cat "$cachefile" | tr -d '[:space:]')" ]]
  then
    echo "[]" > "$cachefile"
  fi

  local cache=$(<"$temp_res")
  
	if [[ -n "$cache" ]]
	then
		jq --arg sel "$1" 'del(.[] | select(.entry == $sel))' "$cachefile" | jq --arg sel "$1" --arg time "$(date +%s)" --arg cc "$cache" --arg size "$(grep -c "^" "$temp_res")" '. += [{entry: $sel, time: $time, cache: $cc, size: $size}]' > "$cachefile.tmp" && mv "$cachefile.tmp" "$cachefile"
	fi
}

read_from_cache () {
	if [[ -s "$cachefile" ]]
	then
		purge_expired_cache
		local entry_found=$(jq --arg sel "$1" '.[] | select(.entry == $sel)' "$cachefile")
		if [[ -n "$entry_found" ]] 
		then
			cache_size=$(echo "$entry_found" | jq -r '.size')
			if [[ $cache_size -lt $search_size ]]
			then
				partial_cache="true"
				playlist_start=$((cache_size+1))
			fi
			cache_result="$entry_found"
		fi
	fi 
}

find_video () {
	local search_url="$1"
	selection=
	url=

	if [[ "$subs_mode" == "true" ]] || [[ "$wl_mode" == "true" ]]
	then
		# check/update this file if sub feed breaks
		if [[ -s "$cookiefile" ]]
		then
			local include_cookies="--cookies $cookiefile"
		else
			>&2 echo "A valid cookies.txt file exist in $data_dir."
			exit 1
		fi
	fi
	
	if [[ "$reverse_mode" == "true" ]] || ([[ "$reverse_mode" == "wl" ]] && [[ "$wl_mode" == "true" ]])
	then
		reverse="--playlist-reverse"
	else
		reverse=
	fi

	# this will be deprecated in future
	if [[ "$use_max_downloads" == "true" ]] || ([[ "$use_max_downloads" == "wl" ]] && [[ "$wl_mode" == "true" ]])
	then
		playlist_ender="--max-downloads"
	else
		playlist_ender="--playlist-end"
	fi

	[[ "$force_no_cache" != "true" ]] && read_from_cache "$search_url"
	
	if [[ -z "$cache_result" ]] || [[ "$partial_cache" == "true" ]]
	then
		temp_res=$(mktemp /tmp/ysp_results.XXXXXXXX)

		if [[ "$partial_cache" == "true" ]]
		then
			local cache_value=$(echo "$cache_result" | jq -r '.cache')
			echo -e "$cache_value" > "$temp_res"
		fi
		
		# using head -n $search_size is only necessary until implementation of
		# https://github.com/ytdl-org/youtube-dl/pull/24487
		youtube-dl -i $reverse --playlist-start $playlist_start $playlist_ender $search_size $include_cookies -j "$search_url" --flat-playlist | head -n $search_size | jq --unbuffered -r '. | "\(.title) :: \(.uploader) => https://www.youtube.com/watch?v=\(.url)"' >> "$temp_res"

		idx=$(cat "$temp_res" | stdbuf -o0 awk 'BEGIN{FS=OFS=" => "}{NF--; print}' | rofi -dmenu -i -p 'Select Video' -no-show-icons -l 10 -scroll-method 0 -format d -async-pre-read 0; exit $?)
		rofi_exit_code=$?

		if [[ -n "$idx" ]] && [[ $idx -ge 1 ]] && [[ -s "$temp_res" ]]
		then
			selection=$(sed "${idx}q;d" "$temp_res")
		fi

		[[ "$force_no_cache" != "true" ]] && write_to_cache "$search_url"
	else
		local cache_value=$(echo "$cache_result" | jq -r '.cache' | head -n $search_size)
		idx=$(echo "$cache_value" | stdbuf -o0 awk 'BEGIN{FS=OFS=" => "}{NF--; print}' \
			| rofi -dmenu -i -p 'Select Video' -no-show-icons -l 10 -scroll-method 0 -format d -async-pre-read 0 &)
		if [[ -n "$idx" ]] && [[ $idx -ge 1 ]]
		then
			selection=$(echo "$cache_value" | sed "${idx}q;d")
		fi
	fi

	url=$(echo "$selection" | awk 'BEGIN{FS=OFS=" => "}{print $NF}')
}

process_args () {
	if [[ $# -gt 0 ]]
	then
		if [[ "$@" =~ --generate-config ]]
		then
			echo "Default config generated in: $default_configfile"
			exit
		elif [[ "$@" =~ --clear-history ]] && [[ "$@" =~ --clear-cache ]]
		then
			clear_history
			clear_cache
			exit
		elif [[ "$@" =~ --clear-history ]]
		then
			clear_history
			exit
		elif [[ "$@" =~ --clear-cache ]]
		then
			clear_cache
			exit
		else
			while [[ $# -gt 0 ]]
			do
				key="$1"
				case $key in
					-s|--subs)
						subs_mode=true
						shift
						;;
					-wl|--watch-later)
						wl_mode=true
						shift
						;;
					-r|--reverse)
						reverse_mode=true
						shift
						;;
					--use-max-downloads)
						use_max_downloads=true
						shift
						;;
					-n|--search-size)
						search_size="$2"
						shift
						shift
						;;
					-C|--force-no-cache)
						force_no_cache=true
						shift
						;;
					-H|--force-no-history)
						force_no_history=true
						shift
						;;
					--config)
						passed_configfile="$2"
						load_config
						shift
						shift
						;;
					-h|--help)
						echo "$(print_help)"
						exit
						;;
					*)
						echo "Unrecognised option $1" >&2
						exit 1
						;;
				esac
			done
		fi
	fi
}

do_search () {
	if [[ "$subs_mode" == "true" ]]
	then
		find_video "https://www.youtube.com/feed/subscriptions"
	elif [[ "$wl_mode" == "true" ]]
	then
		find_video "https://www.youtube.com/playlist?list=WL"
	else
		if [[ "$force_no_history" != "true" ]]
		then
			local history_entries=$(tac "$historyfile")
		else
			history_size=0
		fi
		search_query=$(echo "$history_entries" | rofi -dmenu -i -p "Search YouTube" -no-show-icons -theme-str 'entry { placeholder: "Enter text or select recent search..."; }' -l $([[ $history_size -lt 10 ]] && echo "$history_size" || echo 10) -scroll-method 0)
		if [[ "$search_query" =~ (https?\:\/\/)?(www\.)?(youtube\.com|youtu\.?be)\/.+$ ]]
		then
			selection="$search_query"
			url="${BASH_REMATCH[0]}"
		elif [[ "$search_query" =~ ^@(.+)$ ]]
		then
			sanitised_query=${BASH_REMATCH[1]// /+}
			find_video "https://www.youtube.com/c/$sanitised_query/videos"
		elif [[ -n "$search_query" ]]
		then
			sanitised_query=${search_query// /+}
			find_video "ytsearch$search_size:$sanitised_query"
		else
			exit
		fi
	fi
}

play_video () {
	if [[ -n "$url" ]]
	then
		pkill mpv
		mpv --really-quiet "$url" &
	fi
}

## Main thread

load_config
process_args "$@"
do_search
[[ "$force_no_history" != "true" ]] && update_history
play_video
